export enum Colors {
    Red     = 'Red',
    Orange  = 'Orange',
    Yellow  = 'Yellow',
    Green   = 'Green',
    Mint    = 'Mint',
    Teal    = 'Teal',
    Cyan    = 'Cyan',
    Blue    = 'Blue',
    Indigo  = 'Indigo',
    Purple  = 'Purple',
    Pink    = 'Pink',
    Brown   = 'Brown',
    Gray1   = 'Gray1',
    Gray2   = 'Gray2',
    Gray3   = 'Gray3',
    Gray4   = 'Gray4',
    Gray5   = 'Gray5',
    Gray6   = 'Gray6',
    Contrast = 'Contrast'
}

export const ColorSchemeLight = {
    Red:       '#FF3B30',
    Orange:    '#FF9500',
    Yellow:    '#FFCC00',
    Green:     '#34C759',
    Mint:      '#00C7BE',
    Teal:      '#30B0C7',
    Cyan:      '#32ADE6',
    Blue:      '#007Bff',
    Indigo:    '#5856D8',
    Purple:    '#AF52DE',
    Pink:      '#FF2D54',
    Brown:     '#A2845E',
    Gray1:     '#8E8E93',
    Gray2:     '#AEAEB2',
    Gray3:     '#C7C7CC',
    Gray4:     '#D1D1D6',
    Gray5:     '#E5E5EA',
    Gray6:     '#F2F2F2',
    Contrast:  '#1D1D1F'
}

export const ColorSchemeDark = {
    Red:       '#FF453A',
    Orange:    '#FF9F0A',
    Yellow:    '#FFD60A',
    Green:     '#30D158',
    Mint:      '#66D4CF',
    Teal:      '#40C8E0',
    Cyan:      '#64D2FF',
    Blue:      '#0A84FF',
    Indigo:    '#5E5CE6',
    Purple:    '#BF5AF2',
    Pink:      '#FF375F',
    Brown:     '#AC8E68',
    Gray1:     '#8E8E93',
    Gray2:     '#636366',
    Gray3:     '#48484A',
    Gray4:     '#3A3A3C',
    Gray5:     '#2C2C2E',
    Gray6:     '#1C1C1E',
    Contrast:  '#FFFFFF' 
}

export const ColorPicker = [
    {id : 'Red'},
    {id : 'Orange'},
    {id : 'Yellow'},
    {id : 'Green'},
    {id : 'Mint'},
    {id : 'Teal'},
    {id : 'Cyan'},
    {id : 'Blue'},
    {id : 'Indigo'},
    {id : 'Purple'},
    {id : 'Pink'},
    {id : 'Brown'}
]